name: Calculator App test
run-name: ${{ github.actor }} started the job 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: Setup python
      - uses: actions/setup-python@v3
      - with: 
          python-version: '3.10'

      - name: Create virtual environment
        run: |
          python3.9 -m venv gitenv

      - name: Activate virtual environment
        run: |
          source/envgit/bin/activate

      - name: Install dependencies
        run: pip install pytest

      - name: Run test cases
        run: pytest -v